services:
  controversl.api:
    image: ${DOCKER_REGISTRY-}controverslapi
    build:
      context: .
      dockerfile: src/Controversl.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    volumes:
       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    ports:
      - "5000:5000"

  controversl.client:
    image: ${DOCKER_REGISTRY-}controverslclient
    build:
      context: src/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - controversl.api

  controversl.storybook:
    image: ${DOCKER_REGISTRY-}controverslstorybook
    build:
      context: src/client/
      dockerfile: Dockerfile.storybook
    ports:
      - "6006:6006"

  controversl.docs:
    image: ${DOCKER_REGISTRY-}controversldocs
    build:
      context: docs
    ports:
      - "3001:3001"