//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controversl.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controversl.API.Properties.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a JSON array containing a 10-question quiz based on the theme: &quot;[USERTHEME]&quot;. Each question should present either a controversial fact or a made-up fact related to this theme, and the user must determine whether it is true or false. Ensure the quiz meets the following criteria:
        ///
        ///Diverse subtopics: Cover a variety of angles within the theme to make the quiz engaging.
        ///Surprising or counterintuitive facts: Use facts that challenge common beliefs or present fictional claims.
        ///Balanced mix of &apos;True&apos; and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenerateQuizByThemePrompt {
            get {
                return ResourceManager.GetString("GenerateQuizByThemePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a JSON array containing a 10-question quiz. Each question should present either a controversial fact or a made-up fact on a variety of topics, and the user must determine whether it is true or false. Ensure the quiz meets the following criteria:
        ///
        ///Diverse topics: Cover a range of subjects such as science, history, geography, technology, and pop culture.
        ///Surprising or counterintuitive facts: Use facts that challenge common beliefs or present fictional claims.
        ///Balanced mix of &apos;True&apos; and &apos;False&apos; answer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenerateQuizPrompt {
            get {
                return ResourceManager.GetString("GenerateQuizPrompt", resourceCulture);
            }
        }
    }
}
